# -*- coding: utf-8 -*-
"""Enterprise_Text_to_sql

Automatically generated by Colab.


"""

!pip install -r requirements.txt

import json


def load_metadata(file_path=""):
    with open(file_path, "r", encoding="utf-8") as file:
        data = json.load(file)

    return data["hes"]["tables"]

from sentence_transformers import SentenceTransformer, util


embedding_model = SentenceTransformer("all-MiniLM-L6-v2")


def table_to_text(table):
    table_name = table.get("table_name", "")
    table_desc = table.get("table_discription", "")

    column_parts = []

    for col_name, col_info in table.get("columns", {}).items():
        aliases = col_info.get("aliases", [])
        description = col_info.get("description", "")

        # 🔥 Boost important fields
        boost = ""
        if "last" in col_name or "time" in col_name or "comm" in col_name:
            boost = " IMPORTANT"

        column_parts.append(
            f"""
            Column: {col_name} {boost}
            Aliases: {", ".join(aliases)}
            Description: {description}
            """
        )

    return f"""
    Table: {table_name}
    Description: {table_desc}
    {" ".join(column_parts)}
    """


def select_top_tables(question, tables, top_k=3):
    table_names = []
    table_texts = []

    for table in tables:
        table_names.append(table["table_name"])
        table_texts.append(table_to_text(table))

    table_embeddings = embedding_model.encode(table_texts, convert_to_tensor=True)
    question_embedding = embedding_model.encode(question, convert_to_tensor=True)

    scores = util.cos_sim(question_embedding, table_embeddings)[0]
    top_results = scores.topk(k=top_k)

    selected_tables = []

    for score, index in zip(top_results.values, top_results.indices):
        idx = int(index)

        selected_tables.append({
            "table_name": table_names[idx],
            "score": float(score),
            "table": tables[idx]
        })

    return selected_tables

def build_schema_text(selected_tables):
    schema_text = ""

    for item in selected_tables:
        table = item["table"]

        schema_text += f"\nTable: {table['table_name']}\n"
        schema_text += f"Description: {table.get('table_discription', '')}\n"
        schema_text += "Columns:\n"

        for column_name, column_info in table.get("columns", {}).items():

            # skip secure fields
            if column_info.get("secure") is True:
                continue

            aliases = ", ".join(column_info.get("aliases", []))
            description = column_info.get("description", "")
            validation_rules = column_info.get("validation_rules", [])

            schema_text += f"- {column_name}\n"
            schema_text += f"  Aliases: {aliases}\n"
            schema_text += f"  Description: {description}\n"

            if validation_rules:
                schema_text += f"  Rules: {validation_rules}\n"

        schema_text += "\n"

    return schema_text

def build_prompt(question, schema_text):
    return f"""
You are an expert PostgreSQL query generator.

Your task:
Generate only one PostgreSQL SELECT query.

Rules:
- Use only the given tables and columns.
- Do not use INSERT, UPDATE, DELETE, DROP, ALTER.
- Do not explain the query.
- Do not add markdown.
- If date column has rule "Don't do Casting in Where clause", do not cast it.
- If user does not mention date filter and table has date/time column, limit data to last 30 days.
- Never select secure columns.

Schema:
{schema_text}

User question:
{question}

SQL:
"""

!pip install -U bitsandbytes accelerate

import gc
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_NAME = "defog/sqlcoder-7b-2"

# Clear GPU memory
gc.collect()
torch.cuda.empty_cache()

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True
)

# 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map={"": 0},
    trust_remote_code=True
)

model.eval()


def generate_sql(prompt):
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=4096
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=80,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    result = tokenizer.decode(outputs[0], skip_special_tokens=True)

    if "SQL:" in result:
        sql = result.split("SQL:")[-1].strip()
    else:
        sql = result.strip()

    # clean markdown if model adds it
    sql = sql.replace("```sql", "").replace("```", "").strip()

    return sql

def run_pipeline(question):
    print("\nUser Question:")
    print(question)

    tables = load_metadata("matadata.json")

    selected_tables = select_top_tables(question, tables, top_k=3)

    print("\nTop 3 Selected Tables:")
    for table in selected_tables:
        print(f"- {table['table_name']} | score: {table['score']:.4f}")

    schema_text = build_schema_text(selected_tables)

    print("\nSelected Schema:")
    print(schema_text)

    prompt = build_prompt(question, schema_text)

    sql = generate_sql(prompt)

    print("\nGenerated SQL:")
    print(sql)

    return sql


if __name__ == "__main__":
    question = input("Ask your question: ")
    run_pipeline(question)